#ifndef BASE_MEMORY_MANAGER_H
#define BASE_MEMORY_MANAGER_H

#include <stdio.h>

#define BASE_ADDRESS 0xA00000
#define MAX_AMOUNT_OF_CHUNKS 20
#define CHUNCK_SIZE 2048
#define MAX_ADRESS BASE_ADDRESS + (CHUNCK_SIZE * MAX_AMOUNT_OF_CHUNKS)

void * my_malloc();

#endif